name: clashroyale
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - libcxx=20.1.8
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - cloudpickle==3.1.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - easyocr==1.7.2
      - farama-notifications==0.0.4
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - gymnasium==1.2.2
      - idna==3.11
      - imageio==2.37.2
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mouseinfo==0.1.3
      - mpmath==1.3.0
      - mss==10.1.0
      - networkx==3.4.2
      - ninja==1.13.0
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - psutil==7.1.3
      - pyautogui==0.9.54
      - pyclipper==1.3.0.post6
      - pygetwindow==0.0.9
      - pymsgbox==2.0.1
      - pyobjc==12.1
      - pyobjc-core==12.1
      - pyobjc-framework-accessibility==12.1
      - pyobjc-framework-accounts==12.1
      - pyobjc-framework-addressbook==12.1
      - pyobjc-framework-adservices==12.1
      - pyobjc-framework-adsupport==12.1
      - pyobjc-framework-applescriptkit==12.1
      - pyobjc-framework-applescriptobjc==12.1
      - pyobjc-framework-applicationservices==12.1
      - pyobjc-framework-apptrackingtransparency==12.1
      - pyobjc-framework-audiovideobridging==12.1
      - pyobjc-framework-authenticationservices==12.1
      - pyobjc-framework-automaticassessmentconfiguration==12.1
      - pyobjc-framework-automator==12.1
      - pyobjc-framework-avfoundation==12.1
      - pyobjc-framework-avkit==12.1
      - pyobjc-framework-avrouting==12.1
      - pyobjc-framework-backgroundassets==12.1
      - pyobjc-framework-browserenginekit==12.1
      - pyobjc-framework-businesschat==12.1
      - pyobjc-framework-calendarstore==12.1
      - pyobjc-framework-callkit==12.1
      - pyobjc-framework-carbon==12.1
      - pyobjc-framework-cfnetwork==12.1
      - pyobjc-framework-cinematic==12.1
      - pyobjc-framework-classkit==12.1
      - pyobjc-framework-cloudkit==12.1
      - pyobjc-framework-cocoa==12.1
      - pyobjc-framework-collaboration==12.1
      - pyobjc-framework-colorsync==12.1
      - pyobjc-framework-contacts==12.1
      - pyobjc-framework-contactsui==12.1
      - pyobjc-framework-coreaudio==12.1
      - pyobjc-framework-coreaudiokit==12.1
      - pyobjc-framework-corebluetooth==12.1
      - pyobjc-framework-coredata==12.1
      - pyobjc-framework-corehaptics==12.1
      - pyobjc-framework-corelocation==12.1
      - pyobjc-framework-coremedia==12.1
      - pyobjc-framework-coremediaio==12.1
      - pyobjc-framework-coremidi==12.1
      - pyobjc-framework-coreml==12.1
      - pyobjc-framework-coremotion==12.1
      - pyobjc-framework-coreservices==12.1
      - pyobjc-framework-corespotlight==12.1
      - pyobjc-framework-coretext==12.1
      - pyobjc-framework-corewlan==12.1
      - pyobjc-framework-cryptotokenkit==12.1
      - pyobjc-framework-datadetection==12.1
      - pyobjc-framework-devicecheck==12.1
      - pyobjc-framework-devicediscoveryextension==12.1
      - pyobjc-framework-dictionaryservices==12.1
      - pyobjc-framework-discrecording==12.1
      - pyobjc-framework-discrecordingui==12.1
      - pyobjc-framework-diskarbitration==12.1
      - pyobjc-framework-dvdplayback==12.1
      - pyobjc-framework-eventkit==12.1
      - pyobjc-framework-exceptionhandling==12.1
      - pyobjc-framework-executionpolicy==12.1
      - pyobjc-framework-extensionkit==12.1
      - pyobjc-framework-externalaccessory==12.1
      - pyobjc-framework-fileprovider==12.1
      - pyobjc-framework-fileproviderui==12.1
      - pyobjc-framework-findersync==12.1
      - pyobjc-framework-fsevents==12.1
      - pyobjc-framework-fskit==12.1
      - pyobjc-framework-gamecenter==12.1
      - pyobjc-framework-gamecontroller==12.1
      - pyobjc-framework-gamekit==12.1
      - pyobjc-framework-gameplaykit==12.1
      - pyobjc-framework-healthkit==12.1
      - pyobjc-framework-imagecapturecore==12.1
      - pyobjc-framework-inputmethodkit==12.1
      - pyobjc-framework-installerplugins==12.1
      - pyobjc-framework-instantmessage==12.1
      - pyobjc-framework-intents==12.1
      - pyobjc-framework-intentsui==12.1
      - pyobjc-framework-iobluetooth==12.1
      - pyobjc-framework-iobluetoothui==12.1
      - pyobjc-framework-iosurface==12.1
      - pyobjc-framework-ituneslibrary==12.1
      - pyobjc-framework-kernelmanagement==12.1
      - pyobjc-framework-latentsemanticmapping==12.1
      - pyobjc-framework-launchservices==12.1
      - pyobjc-framework-libdispatch==12.1
      - pyobjc-framework-libxpc==12.1
      - pyobjc-framework-linkpresentation==12.1
      - pyobjc-framework-localauthentication==12.1
      - pyobjc-framework-localauthenticationembeddedui==12.1
      - pyobjc-framework-mailkit==12.1
      - pyobjc-framework-mapkit==12.1
      - pyobjc-framework-mediaaccessibility==12.1
      - pyobjc-framework-mediaextension==12.1
      - pyobjc-framework-medialibrary==12.1
      - pyobjc-framework-mediaplayer==12.1
      - pyobjc-framework-mediatoolbox==12.1
      - pyobjc-framework-metal==12.1
      - pyobjc-framework-metalfx==12.1
      - pyobjc-framework-metalkit==12.1
      - pyobjc-framework-metalperformanceshaders==12.1
      - pyobjc-framework-metalperformanceshadersgraph==12.1
      - pyobjc-framework-metrickit==12.1
      - pyobjc-framework-mlcompute==12.1
      - pyobjc-framework-modelio==12.1
      - pyobjc-framework-multipeerconnectivity==12.1
      - pyobjc-framework-naturallanguage==12.1
      - pyobjc-framework-netfs==12.1
      - pyobjc-framework-network==12.1
      - pyobjc-framework-networkextension==12.1
      - pyobjc-framework-notificationcenter==12.1
      - pyobjc-framework-opendirectory==12.1
      - pyobjc-framework-osakit==12.1
      - pyobjc-framework-oslog==12.1
      - pyobjc-framework-passkit==12.1
      - pyobjc-framework-pencilkit==12.1
      - pyobjc-framework-phase==12.1
      - pyobjc-framework-photos==12.1
      - pyobjc-framework-photosui==12.1
      - pyobjc-framework-preferencepanes==12.1
      - pyobjc-framework-pushkit==12.1
      - pyobjc-framework-quartz==12.1
      - pyobjc-framework-quicklookthumbnailing==12.1
      - pyobjc-framework-replaykit==12.1
      - pyobjc-framework-safariservices==12.1
      - pyobjc-framework-safetykit==12.1
      - pyobjc-framework-scenekit==12.1
      - pyobjc-framework-screencapturekit==12.1
      - pyobjc-framework-screensaver==12.1
      - pyobjc-framework-screentime==12.1
      - pyobjc-framework-scriptingbridge==12.1
      - pyobjc-framework-searchkit==12.1
      - pyobjc-framework-security==12.1
      - pyobjc-framework-securityfoundation==12.1
      - pyobjc-framework-securityinterface==12.1
      - pyobjc-framework-securityui==12.1
      - pyobjc-framework-sensitivecontentanalysis==12.1
      - pyobjc-framework-servicemanagement==12.1
      - pyobjc-framework-sharedwithyou==12.1
      - pyobjc-framework-sharedwithyoucore==12.1
      - pyobjc-framework-shazamkit==12.1
      - pyobjc-framework-social==12.1
      - pyobjc-framework-soundanalysis==12.1
      - pyobjc-framework-speech==12.1
      - pyobjc-framework-spritekit==12.1
      - pyobjc-framework-storekit==12.1
      - pyobjc-framework-symbols==12.1
      - pyobjc-framework-syncservices==12.1
      - pyobjc-framework-systemconfiguration==12.1
      - pyobjc-framework-systemextensions==12.1
      - pyobjc-framework-threadnetwork==12.1
      - pyobjc-framework-uniformtypeidentifiers==12.1
      - pyobjc-framework-usernotifications==12.1
      - pyobjc-framework-usernotificationsui==12.1
      - pyobjc-framework-videosubscriberaccount==12.1
      - pyobjc-framework-videotoolbox==12.1
      - pyobjc-framework-virtualization==12.1
      - pyobjc-framework-vision==12.1
      - pyobjc-framework-webkit==12.1
      - pyparsing==3.2.5
      - pyperclip==1.11.0
      - pyrect==0.2.0
      - pyscreeze==1.0.1
      - pytesseract==0.3.13
      - python-bidi==0.6.7
      - python-dateutil==2.9.0.post0
      - pytweening==1.2.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - rubicon-objc==0.5.2
      - sb3-contrib==2.7.0
      - scikit-image==0.25.2
      - scipy==1.15.3
      - shapely==2.1.2
      - six==1.17.0
      - stable-baselines3==2.7.0
      - sympy==1.14.0
      - tifffile==2025.5.10
      - torch==2.9.1
      - torchvision==0.24.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - ultralytics==8.3.231
      - ultralytics-thop==2.0.18
      - urllib3==2.5.0
prefix: /opt/miniconda3/envs/clashroyale
